/**
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ChartDataColumn model module.
* @module com.nimbits.io/ChartDataColumn
* @version 5.0
*/
export default class ChartDataColumn {
    /**
    * Constructs a new <code>ChartDataColumn</code>.
    * @alias module:com.nimbits.io/ChartDataColumn
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ChartDataColumn</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.nimbits.io/ChartDataColumn} obj Optional instance to populate.
    * @return {module:com.nimbits.io/ChartDataColumn} The populated <code>ChartDataColumn</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChartDataColumn();

            
            
            

            if (data.hasOwnProperty('v')) {
                obj['v'] = ApiClient.convertToType(data['v'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {Object} v
    */
    v = undefined;








}


