/**
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ChartColumnDefinition model module.
* @module com.nimbits.io/ChartColumnDefinition
* @version 5.0
*/
export default class ChartColumnDefinition {
    /**
    * Constructs a new <code>ChartColumnDefinition</code>.
    * @alias module:com.nimbits.io/ChartColumnDefinition
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ChartColumnDefinition</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.nimbits.io/ChartColumnDefinition} obj Optional instance to populate.
    * @return {module:com.nimbits.io/ChartColumnDefinition} The populated <code>ChartColumnDefinition</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChartColumnDefinition();

            
            
            

            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} label
    */
    label = undefined;
    /**
    * @member {String} type
    */
    type = undefined;








}


