/**
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ChartColumnDefinition from './ChartColumnDefinition';
import Row from './Row';





/**
* The ChartDTO model module.
* @module com.nimbits.io/ChartDTO
* @version 5.0
*/
export default class ChartDTO {
    /**
    * Constructs a new <code>ChartDTO</code>.
    * @alias module:com.nimbits.io/ChartDTO
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ChartDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.nimbits.io/ChartDTO} obj Optional instance to populate.
    * @return {module:com.nimbits.io/ChartDTO} The populated <code>ChartDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChartDTO();

            
            
            

            if (data.hasOwnProperty('cols')) {
                obj['cols'] = ApiClient.convertToType(data['cols'], [ChartColumnDefinition]);
            }
            if (data.hasOwnProperty('p')) {
                obj['p'] = ApiClient.convertToType(data['p'], Object);
            }
            if (data.hasOwnProperty('rows')) {
                obj['rows'] = ApiClient.convertToType(data['rows'], [Row]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:com.nimbits.io/ChartColumnDefinition>} cols
    */
    cols = undefined;
    /**
    * @member {Object} p
    */
    p = undefined;
    /**
    * @member {Array.<module:com.nimbits.io/Row>} rows
    */
    rows = undefined;








}


