/**
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ChartDataColumn from './ChartDataColumn';





/**
* The Row model module.
* @module com.nimbits.io/Row
* @version 5.0
*/
export default class Row {
    /**
    * Constructs a new <code>Row</code>.
    * @alias module:com.nimbits.io/Row
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Row</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:com.nimbits.io/Row} obj Optional instance to populate.
    * @return {module:com.nimbits.io/Row} The populated <code>Row</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Row();

            
            
            

            if (data.hasOwnProperty('c')) {
                obj['c'] = ApiClient.convertToType(data['c'], [ChartDataColumn]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:com.nimbits.io/ChartDataColumn>} c
    */
    c = undefined;








}


