/*
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nimbits.io;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nimbits.io.ChartColumnDefinition;
import com.nimbits.io.Row;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ChartDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-01T12:54:28.644-04:00")
public class ChartDTO {
  @SerializedName("cols")
  private List<ChartColumnDefinition> cols = null;

  @SerializedName("p")
  private Object p = null;

  @SerializedName("rows")
  private List<Row> rows = null;

  public ChartDTO cols(List<ChartColumnDefinition> cols) {
    this.cols = cols;
    return this;
  }

  public ChartDTO addColsItem(ChartColumnDefinition colsItem) {
    if (this.cols == null) {
      this.cols = new ArrayList<ChartColumnDefinition>();
    }
    this.cols.add(colsItem);
    return this;
  }

   /**
   * Get cols
   * @return cols
  **/
  @ApiModelProperty(value = "")
  public List<ChartColumnDefinition> getCols() {
    return cols;
  }

  public void setCols(List<ChartColumnDefinition> cols) {
    this.cols = cols;
  }

  public ChartDTO p(Object p) {
    this.p = p;
    return this;
  }

   /**
   * Get p
   * @return p
  **/
  @ApiModelProperty(value = "")
  public Object getP() {
    return p;
  }

  public void setP(Object p) {
    this.p = p;
  }

  public ChartDTO rows(List<Row> rows) {
    this.rows = rows;
    return this;
  }

  public ChartDTO addRowsItem(Row rowsItem) {
    if (this.rows == null) {
      this.rows = new ArrayList<Row>();
    }
    this.rows.add(rowsItem);
    return this;
  }

   /**
   * Get rows
   * @return rows
  **/
  @ApiModelProperty(value = "")
  public List<Row> getRows() {
    return rows;
  }

  public void setRows(List<Row> rows) {
    this.rows = rows;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChartDTO chartDTO = (ChartDTO) o;
    return Objects.equals(this.cols, chartDTO.cols) &&
        Objects.equals(this.p, chartDTO.p) &&
        Objects.equals(this.rows, chartDTO.rows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cols, p, rows);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChartDTO {\n");
    
    sb.append("    cols: ").append(toIndentedString(cols)).append("\n");
    sb.append("    p: ").append(toIndentedString(p)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

