/**
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ChartColumnDefinition from './com.nimbits.io/ChartColumnDefinition';
import ChartDTO from './com.nimbits.io/ChartDTO';
import ChartDataColumn from './com.nimbits.io/ChartDataColumn';
import EntityGroup from './com.nimbits.io/EntityGroup';
import ResponseEntity from './com.nimbits.io/ResponseEntity';
import Row from './com.nimbits.io/Row';
import Snapshot from './com.nimbits.io/Snapshot';
import Topic from './com.nimbits.io/Topic';
import EntityApi from './com.nimbits/EntityApi';
import GroupApi from './com.nimbits/GroupApi';
import SnapshotApi from './com.nimbits/SnapshotApi';
import TableApi from './com.nimbits/TableApi';
import TopicApi from './com.nimbits/TopicApi';


/**
* Nimbits_Server_Provides_deep_automation_via_a_REST_API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var NimbitsApi = require('index'); // See note below*.
* var xxxSvc = new NimbitsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new NimbitsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new NimbitsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new NimbitsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 5.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ChartColumnDefinition model constructor.
     * @property {module:com.nimbits.io/ChartColumnDefinition}
     */
    ChartColumnDefinition,

    /**
     * The ChartDTO model constructor.
     * @property {module:com.nimbits.io/ChartDTO}
     */
    ChartDTO,

    /**
     * The ChartDataColumn model constructor.
     * @property {module:com.nimbits.io/ChartDataColumn}
     */
    ChartDataColumn,

    /**
     * The EntityGroup model constructor.
     * @property {module:com.nimbits.io/EntityGroup}
     */
    EntityGroup,

    /**
     * The ResponseEntity model constructor.
     * @property {module:com.nimbits.io/ResponseEntity}
     */
    ResponseEntity,

    /**
     * The Row model constructor.
     * @property {module:com.nimbits.io/Row}
     */
    Row,

    /**
     * The Snapshot model constructor.
     * @property {module:com.nimbits.io/Snapshot}
     */
    Snapshot,

    /**
     * The Topic model constructor.
     * @property {module:com.nimbits.io/Topic}
     */
    Topic,

    /**
    * The EntityApi service constructor.
    * @property {module:com.nimbits/EntityApi}
    */
    EntityApi,

    /**
    * The GroupApi service constructor.
    * @property {module:com.nimbits/GroupApi}
    */
    GroupApi,

    /**
    * The SnapshotApi service constructor.
    * @property {module:com.nimbits/SnapshotApi}
    */
    SnapshotApi,

    /**
    * The TableApi service constructor.
    * @property {module:com.nimbits/TableApi}
    */
    TableApi,

    /**
    * The TopicApi service constructor.
    * @property {module:com.nimbits/TopicApi}
    */
    TopicApi
};
