/**
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.NimbitsApi);
  }
}(this, function(expect, NimbitsApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new NimbitsApi.ChartDTO();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChartDTO', function() {
    it('should create an instance of ChartDTO', function() {
      // uncomment below and update the code to test ChartDTO
      //var instane = new NimbitsApi.ChartDTO();
      //expect(instance).to.be.a(NimbitsApi.ChartDTO);
    });

    it('should have the property cols (base name: "cols")', function() {
      // uncomment below and update the code to test the property cols
      //var instane = new NimbitsApi.ChartDTO();
      //expect(instance).to.be();
    });

    it('should have the property p (base name: "p")', function() {
      // uncomment below and update the code to test the property p
      //var instane = new NimbitsApi.ChartDTO();
      //expect(instance).to.be();
    });

    it('should have the property rows (base name: "rows")', function() {
      // uncomment below and update the code to test the property rows
      //var instane = new NimbitsApi.ChartDTO();
      //expect(instance).to.be();
    });

  });

}));
