#!/bin/sh
H2=/opt/nimbits/lib/h2.jar
DE=/etc/default/jetty
DEBAK=/tmp/jetty
D=/opt/nimbits/database
F=/tmp/nimbitsdb.zip

if [ -f "$H2" ]; then
    if [ -d "$D" ]; then
        echo "Backing up existing database to /tmp/nimbitsdb.zip"
        java -cp /opt/nimbits/lib/h2.jar org.h2.tools.Backup  -file ${F} -dir ${D}
    fi
fi

if [ -f "$DE" ]; then

        echo "backing up settings"
        cp -vf "$DE" "$DEBAK"


fi



