/**
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EntityGroup from '../com.nimbits.io/EntityGroup';
import Topic from '../com.nimbits.io/Topic';

/**
* Entity service.
* @module com.nimbits/EntityApi
* @version 5.0
*/
export default class EntityApi {

    /**
    * Constructs a new EntityApi. 
    * @alias module:com.nimbits/EntityApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addTopic operation.
     * @callback module:com.nimbits/EntityApi~addTopicCallback
     * @param {String} error Error message, if any.
     * @param {module:com.nimbits.io/Topic} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * AddTopic
     * Post a new Topic
     * @param {String} xApiKey x-api-key
     * @param {module:com.nimbits.io/Topic} topic topic
     * @param {module:com.nimbits/EntityApi~addTopicCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.nimbits.io/Topic}
     */
    addTopic(xApiKey, topic, callback) {
      let postBody = topic;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling addTopic");
      }

      // verify the required parameter 'topic' is set
      if (topic === undefined || topic === null) {
        throw new Error("Missing the required parameter 'topic' when calling addTopic");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'x-api-key': xApiKey
      };
      let formParams = {
      };

      let authNames = ['x-api-key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Topic;

      return this.apiClient.callApi(
        '/v5_0/api/entity/topic', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTopic operation.
     * @callback module:com.nimbits/EntityApi~deleteTopicCallback
     * @param {String} error Error message, if any.
     * @param {module:com.nimbits.io/Topic} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * DeleteTopic
     * Delete a Topic
     * @param {String} xApiKey x-api-key
     * @param {String} id id
     * @param {module:com.nimbits/EntityApi~deleteTopicCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.nimbits.io/Topic}
     */
    deleteTopic(xApiKey, id, callback) {
      let postBody = null;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling deleteTopic");
      }

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling deleteTopic");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'x-api-key': xApiKey
      };
      let formParams = {
      };

      let authNames = ['x-api-key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Topic;

      return this.apiClient.callApi(
        '/v5_0/api/entity/topic/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getGroup operation.
     * @callback module:com.nimbits/EntityApi~getGroupCallback
     * @param {String} error Error message, if any.
     * @param {module:com.nimbits.io/EntityGroup} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetGroup
     * Get Groups With all Connected Entities
     * @param {String} xApiKey x-api-key
     * @param {String} id id
     * @param {module:com.nimbits/EntityApi~getGroupCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.nimbits.io/EntityGroup}
     */
    getGroup(xApiKey, id, callback) {
      let postBody = null;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling getGroup");
      }

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getGroup");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'x-api-key': xApiKey
      };
      let formParams = {
      };

      let authNames = ['x-api-key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EntityGroup;

      return this.apiClient.callApi(
        '/v5_0/api/group/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getTopic operation.
     * @callback module:com.nimbits/EntityApi~getTopicCallback
     * @param {String} error Error message, if any.
     * @param {module:com.nimbits.io/Topic} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetTopic
     * Get a Topic
     * @param {String} xApiKey x-api-key
     * @param {String} id id
     * @param {module:com.nimbits/EntityApi~getTopicCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.nimbits.io/Topic}
     */
    getTopic(xApiKey, id, callback) {
      let postBody = null;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling getTopic");
      }

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getTopic");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'x-api-key': xApiKey
      };
      let formParams = {
      };

      let authNames = ['x-api-key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Topic;

      return this.apiClient.callApi(
        '/v5_0/api/entity/topic/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
