/**
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EntityGroup from '../com.nimbits.io/EntityGroup';

/**
* Group service.
* @module com.nimbits/GroupApi
* @version 5.0
*/
export default class GroupApi {

    /**
    * Constructs a new GroupApi. 
    * @alias module:com.nimbits/GroupApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getGroup operation.
     * @callback module:com.nimbits/GroupApi~getGroupCallback
     * @param {String} error Error message, if any.
     * @param {module:com.nimbits.io/EntityGroup} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetGroup
     * Get Groups With all Connected Entities
     * @param {String} xApiKey x-api-key
     * @param {String} id id
     * @param {module:com.nimbits/GroupApi~getGroupCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:com.nimbits.io/EntityGroup}
     */
    getGroup(xApiKey, id, callback) {
      let postBody = null;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling getGroup");
      }

      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getGroup");
      }


      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
        'x-api-key': xApiKey
      };
      let formParams = {
      };

      let authNames = ['x-api-key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = EntityGroup;

      return this.apiClient.callApi(
        '/v5_0/api/group/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getGroups operation.
     * @callback module:com.nimbits/GroupApi~getGroupsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:com.nimbits.io/EntityGroup>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetGroups
     * Get All Groups For an Account
     * @param {String} xApiKey x-api-key
     * @param {module:com.nimbits/GroupApi~getGroupsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:com.nimbits.io/EntityGroup>}
     */
    getGroups(xApiKey, callback) {
      let postBody = null;

      // verify the required parameter 'xApiKey' is set
      if (xApiKey === undefined || xApiKey === null) {
        throw new Error("Missing the required parameter 'xApiKey' when calling getGroups");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
        'x-api-key': xApiKey
      };
      let formParams = {
      };

      let authNames = ['x-api-key'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [EntityGroup];

      return this.apiClient.callApi(
        '/v5_0/api/group', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
