/*
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nimbits;

import com.ApiException;
import com.nimbits.io.EntityGroup;
import com.nimbits.io.Topic;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EntityApi
 */
@Ignore
public class EntityApiTest {

    private final EntityApi api = new EntityApi();

    
    /**
     * AddTopic
     *
     * Post a new Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTopicTest() throws ApiException {
        String xApiKey = null;
        Topic topic = null;
        Topic response = api.addTopic(xApiKey, topic);

        // TODO: test validations
    }
    
    /**
     * DeleteTopic
     *
     * Delete a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTopicTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        Topic response = api.deleteTopic(xApiKey, id);

        // TODO: test validations
    }
    
    /**
     * GetGroup
     *
     * Get Groups With all Connected Entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        EntityGroup response = api.getGroup(xApiKey, id);

        // TODO: test validations
    }
    
    /**
     * GetTopic
     *
     * Get a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopicTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        Topic response = api.getTopic(xApiKey, id);

        // TODO: test validations
    }
    
}
