/*
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nimbits;

import com.ApiException;
import com.nimbits.io.EntityGroup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupApi
 */
@Ignore
public class GroupApiTest {

    private final GroupApi api = new GroupApi();

    
    /**
     * GetGroup
     *
     * Get Groups With all Connected Entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        EntityGroup response = api.getGroup(xApiKey, id);

        // TODO: test validations
    }
    
    /**
     * GetGroups
     *
     * Get All Groups For an Account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupsTest() throws ApiException {
        String xApiKey = null;
        List<EntityGroup> response = api.getGroups(xApiKey);

        // TODO: test validations
    }
    
}
