/*
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nimbits;

import com.ApiException;
import com.nimbits.io.Snapshot;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SnapshotApi
 */
@Ignore
public class SnapshotApiTest {

    private final SnapshotApi api = new SnapshotApi();

    
    /**
     * GetSnapshot
     *
     * Get Snapshot for a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSnapshotTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        Snapshot response = api.getSnapshot(xApiKey, id);

        // TODO: test validations
    }
    
    /**
     * PostSnapshot
     *
     * Post a Snapshot to a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postSnapshotTest() throws ApiException {
        String xApiKey = null;
        Snapshot value = null;
        String id = null;
        Snapshot response = api.postSnapshot(xApiKey, value, id);

        // TODO: test validations
    }
    
}
