/*
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nimbits;

import com.ApiException;
import com.nimbits.io.ChartDTO;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TableApi
 */
@Ignore
public class TableApiTest {

    private final TableApi api = new TableApi();

    
    /**
     * GetDataTable
     *
     * Get A Data Table For a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDataTableTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        String start = null;
        String end = null;
        String count = null;
        String mask = null;
        ChartDTO response = api.getDataTable(xApiKey, id, start, end, count, mask);

        // TODO: test validations
    }
    
}
