/*
 * Nimbits API
 * Nimbits Server Provides deep automation via a REST API
 *
 * OpenAPI spec version: 5.0
 * Contact: support@nimbits.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.nimbits;

import com.ApiException;
import com.nimbits.io.ChartDTO;
import com.nimbits.io.EntityGroup;
import com.nimbits.io.Snapshot;
import com.nimbits.io.Topic;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TopicApi
 */
@Ignore
public class TopicApiTest {

    private final TopicApi api = new TopicApi();

    
    /**
     * AddTopic
     *
     * Post a new Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addTopicTest() throws ApiException {
        String xApiKey = null;
        Topic topic = null;
        Topic response = api.addTopic(xApiKey, topic);

        // TODO: test validations
    }
    
    /**
     * DeleteTopic
     *
     * Delete a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTopicTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        Topic response = api.deleteTopic(xApiKey, id);

        // TODO: test validations
    }
    
    /**
     * GetDataTable
     *
     * Get A Data Table For a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDataTableTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        String start = null;
        String end = null;
        String count = null;
        String mask = null;
        ChartDTO response = api.getDataTable(xApiKey, id, start, end, count, mask);

        // TODO: test validations
    }
    
    /**
     * GetGroup
     *
     * Get Groups With all Connected Entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        EntityGroup response = api.getGroup(xApiKey, id);

        // TODO: test validations
    }
    
    /**
     * GetGroups
     *
     * Get All Groups For an Account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGroupsTest() throws ApiException {
        String xApiKey = null;
        List<EntityGroup> response = api.getGroups(xApiKey);

        // TODO: test validations
    }
    
    /**
     * GetSnapshot
     *
     * Get Snapshot for a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSnapshotTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        Snapshot response = api.getSnapshot(xApiKey, id);

        // TODO: test validations
    }
    
    /**
     * GetTopic
     *
     * Get a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTopicTest() throws ApiException {
        String xApiKey = null;
        String id = null;
        Topic response = api.getTopic(xApiKey, id);

        // TODO: test validations
    }
    
    /**
     * PostSnapshot
     *
     * Post a Snapshot to a Topic
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postSnapshotTest() throws ApiException {
        String xApiKey = null;
        Snapshot value = null;
        String id = null;
        Snapshot response = api.postSnapshot(xApiKey, value, id);

        // TODO: test validations
    }
    
}
